-- ┌───────────────┐
-- │ C++ behaviour │
-- └───────────────┘
--
-- On top of what '$VIMRUNTIME/ftplugin/cpp.vim' already does - it sources
-- 'c.vim' and 'c.lua', so `commentstring`, `include`, `define`, `omnifunc` and
-- `cindent` all come from there.
--
-- NOTE: a '.h' file is `cpp` here and not `c`, whatever it contains:
-- `M.header()` of '$VIMRUNTIME/lua/vim/filetype/detect.lua' only looks for
-- Objective-C markers and then falls back to `cpp` unless `g:c_syntax_for_h` is
-- set. That global belongs to the '.nvim.lua' of a C-only project (`:h 'exrc'`,
-- skill `nvim-project-environment`), not to this shared config.
--
-- Everything this config adds for the two languages - folds, `:make`, project
-- `'path'`, `:Run` - is written once, in 'after/ftplugin/c.lua', and NOTHING
-- HERE SOURCES IT: `$VIMRUNTIME/ftplugin/cpp.vim` already runs
-- `runtime! ftplugin/c.vim ftplugin/c.lua` for every `cpp` buffer, and
-- 'runtimepath' carries this config's directory twice - once as itself, once
-- as its own `.../after` entry, which Neovim appends for every config
-- (`:set runtimepath?`). `ftplugin/c.lua`, resolved against that second
-- entry, IS `after/ftplugin/c.lua` - our file.
--
-- NOTE: an earlier version of this file added its own
-- `vim.cmd('runtime! after/ftplugin/c.lua')`, sourcing it a SECOND time on
-- every `cpp` buffer - harmless for the idempotent option assignments, but
-- fatal for `require('config.run').command()`'s `:Run` definition, whose
-- `b:undo_ftplugin` line (`delcommand Run`) was then registered twice, and
-- the second `delcommand` raised `E184` on the next filetype change.
-- Measured: a load counter added to 'c.lua' showed it sourced twice per
-- `cpp` buffer with the explicit call in place, once without it. `.c` is
-- still the filetype Neovim's own detector falls back to for a header-less
-- file, and 'after/ftplugin/c.lua' is the one that has to work on its own
-- without this file's help.
