-- ┌───────────────┐
-- │ C++ behaviour │
-- └───────────────┘
--
-- On top of what '$VIMRUNTIME/ftplugin/cpp.vim' already does - it sources
-- 'c.vim' and 'c.lua', so `commentstring`, `include`, `define`, `omnifunc` and
-- `cindent` all come from there.
--
-- NOTE: a '.h' file is `cpp` here and not `c`, whatever it contains:
-- `M.header()` of '$VIMRUNTIME/lua/vim/filetype/detect.lua' only looks for
-- Objective-C markers and then falls back to `cpp` unless `g:c_syntax_for_h` is
-- set. That global belongs to the '.nvim.lua' of a C-only project (`:h 'exrc'`,
-- skill `nvim-project-environment`), not to this shared config.
--
-- Everything this config adds for the two languages - folds, `:make`, project
-- `'path'`, `:Run` - is the same work whichever of the two a checkout builds
-- (the projects sampled here build both from one 'CMakeLists.txt' or
-- 'Makefile'), so it is written once in 'after/ftplugin/c.lua' and sourced
-- from here (`:h runtime!`) rather than the other way around: `c` is the
-- filetype Neovim's own detector falls back to for a header-less file, so it
-- is the one that has to work on its own.
vim.cmd('runtime! after/ftplugin/c.lua')
